// Code generated by goctl. DO NOT EDIT.
// Source: giftRpc.proto

package server

import (
	"context"

	"social-im/app/gift/cmd/rpc/internal/logic"
	"social-im/app/gift/cmd/rpc/internal/svc"
	"social-im/app/gift/cmd/rpc/pb"
)

type GiftRpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedGiftRpcServer
}

func NewGiftRpcServer(svcCtx *svc.ServiceContext) *GiftRpcServer {
	return &GiftRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *GiftRpcServer) Send(ctx context.Context, in *pb.GiftSendReq) (*pb.GiftSendResp, error) {
	l := logic.NewSendLogic(ctx, s.svcCtx)
	return l.Send(in)
}

func (s *GiftRpcServer) UpdateBag(ctx context.Context, in *pb.GiftUpdateBagReq) (*pb.GiftUpdateBagResp, error) {
	l := logic.NewUpdateBagLogic(ctx, s.svcCtx)
	return l.UpdateBag(in)
}

func (s *GiftRpcServer) UpdateAttr(ctx context.Context, in *pb.GiftUpdateAttrReq) (*pb.GiftUpdateAttrResp, error) {
	l := logic.NewUpdateAttrLogic(ctx, s.svcCtx)
	return l.UpdateAttr(in)
}
