// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: adminRpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackImgConf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url      string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	SmallUrl string `protobuf:"bytes,2,opt,name=SmallUrl,proto3" json:"SmallUrl,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Key      string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Tag      string `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	Id       int64  `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	Type     int64  `protobuf:"varint,7,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *BackImgConf) Reset() {
	*x = BackImgConf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminRpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackImgConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackImgConf) ProtoMessage() {}

func (x *BackImgConf) ProtoReflect() protoreflect.Message {
	mi := &file_adminRpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackImgConf.ProtoReflect.Descriptor instead.
func (*BackImgConf) Descriptor() ([]byte, []int) {
	return file_adminRpc_proto_rawDescGZIP(), []int{0}
}

func (x *BackImgConf) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BackImgConf) GetSmallUrl() string {
	if x != nil {
		return x.SmallUrl
	}
	return ""
}

func (x *BackImgConf) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackImgConf) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *BackImgConf) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *BackImgConf) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BackImgConf) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type DictionaryDetailConf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label        string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value        int64  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	DictionaryId int64  `protobuf:"varint,3,opt,name=DictionaryId,proto3" json:"DictionaryId,omitempty"`
}

func (x *DictionaryDetailConf) Reset() {
	*x = DictionaryDetailConf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminRpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictionaryDetailConf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryDetailConf) ProtoMessage() {}

func (x *DictionaryDetailConf) ProtoReflect() protoreflect.Message {
	mi := &file_adminRpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryDetailConf.ProtoReflect.Descriptor instead.
func (*DictionaryDetailConf) Descriptor() ([]byte, []int) {
	return file_adminRpc_proto_rawDescGZIP(), []int{1}
}

func (x *DictionaryDetailConf) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DictionaryDetailConf) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *DictionaryDetailConf) GetDictionaryId() int64 {
	if x != nil {
		return x.DictionaryId
	}
	return 0
}

type BackgroundImgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastId   int64 `protobuf:"varint,1,opt,name=lastId,proto3" json:"lastId,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Type     int64 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *BackgroundImgReq) Reset() {
	*x = BackgroundImgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminRpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackgroundImgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackgroundImgReq) ProtoMessage() {}

func (x *BackgroundImgReq) ProtoReflect() protoreflect.Message {
	mi := &file_adminRpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackgroundImgReq.ProtoReflect.Descriptor instead.
func (*BackgroundImgReq) Descriptor() ([]byte, []int) {
	return file_adminRpc_proto_rawDescGZIP(), []int{2}
}

func (x *BackgroundImgReq) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *BackgroundImgReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *BackgroundImgReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type BackgroundImgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64          `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*BackImgConf `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *BackgroundImgResp) Reset() {
	*x = BackgroundImgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminRpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackgroundImgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackgroundImgResp) ProtoMessage() {}

func (x *BackgroundImgResp) ProtoReflect() protoreflect.Message {
	mi := &file_adminRpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackgroundImgResp.ProtoReflect.Descriptor instead.
func (*BackgroundImgResp) Descriptor() ([]byte, []int) {
	return file_adminRpc_proto_rawDescGZIP(), []int{3}
}

func (x *BackgroundImgResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BackgroundImgResp) GetList() []*BackImgConf {
	if x != nil {
		return x.List
	}
	return nil
}

type DictionaryGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DictionaryType string `protobuf:"bytes,1,opt,name=dictionaryType,proto3" json:"dictionaryType,omitempty"`
}

func (x *DictionaryGetReq) Reset() {
	*x = DictionaryGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminRpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictionaryGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryGetReq) ProtoMessage() {}

func (x *DictionaryGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_adminRpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryGetReq.ProtoReflect.Descriptor instead.
func (*DictionaryGetReq) Descriptor() ([]byte, []int) {
	return file_adminRpc_proto_rawDescGZIP(), []int{4}
}

func (x *DictionaryGetReq) GetDictionaryType() string {
	if x != nil {
		return x.DictionaryType
	}
	return ""
}

type DictionaryGetResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*DictionaryDetailConf `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *DictionaryGetResp) Reset() {
	*x = DictionaryGetResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminRpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictionaryGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryGetResp) ProtoMessage() {}

func (x *DictionaryGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_adminRpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryGetResp.ProtoReflect.Descriptor instead.
func (*DictionaryGetResp) Descriptor() ([]byte, []int) {
	return file_adminRpc_proto_rawDescGZIP(), []int{5}
}

func (x *DictionaryGetResp) GetList() []*DictionaryDetailConf {
	if x != nil {
		return x.List
	}
	return nil
}

type ProjectConfigInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ConfigType  int64  `protobuf:"varint,2,opt,name=ConfigType,proto3" json:"ConfigType,omitempty"`
	ConfigName  string `protobuf:"bytes,3,opt,name=ConfigName,proto3" json:"ConfigName,omitempty"`
	ConfigKey   string `protobuf:"bytes,4,opt,name=ConfigKey,proto3" json:"ConfigKey,omitempty"`
	ConfigValue string `protobuf:"bytes,5,opt,name=ConfigValue,proto3" json:"ConfigValue,omitempty"`
}

func (x *ProjectConfigInfo) Reset() {
	*x = ProjectConfigInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminRpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectConfigInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectConfigInfo) ProtoMessage() {}

func (x *ProjectConfigInfo) ProtoReflect() protoreflect.Message {
	mi := &file_adminRpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectConfigInfo.ProtoReflect.Descriptor instead.
func (*ProjectConfigInfo) Descriptor() ([]byte, []int) {
	return file_adminRpc_proto_rawDescGZIP(), []int{6}
}

func (x *ProjectConfigInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProjectConfigInfo) GetConfigType() int64 {
	if x != nil {
		return x.ConfigType
	}
	return 0
}

func (x *ProjectConfigInfo) GetConfigName() string {
	if x != nil {
		return x.ConfigName
	}
	return ""
}

func (x *ProjectConfigInfo) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

func (x *ProjectConfigInfo) GetConfigValue() string {
	if x != nil {
		return x.ConfigValue
	}
	return ""
}

type ProjectConfigDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigType int64  `protobuf:"varint,1,opt,name=ConfigType,proto3" json:"ConfigType,omitempty"`
	ConfigKey  string `protobuf:"bytes,2,opt,name=ConfigKey,proto3" json:"ConfigKey,omitempty"`
}

func (x *ProjectConfigDetailReq) Reset() {
	*x = ProjectConfigDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminRpc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectConfigDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectConfigDetailReq) ProtoMessage() {}

func (x *ProjectConfigDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_adminRpc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectConfigDetailReq.ProtoReflect.Descriptor instead.
func (*ProjectConfigDetailReq) Descriptor() ([]byte, []int) {
	return file_adminRpc_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectConfigDetailReq) GetConfigType() int64 {
	if x != nil {
		return x.ConfigType
	}
	return 0
}

func (x *ProjectConfigDetailReq) GetConfigKey() string {
	if x != nil {
		return x.ConfigKey
	}
	return ""
}

type ProjectConfigDetailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectConfigInfo *ProjectConfigInfo `protobuf:"bytes,1,opt,name=projectConfigInfo,proto3" json:"projectConfigInfo,omitempty"`
}

func (x *ProjectConfigDetailResp) Reset() {
	*x = ProjectConfigDetailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminRpc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProjectConfigDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectConfigDetailResp) ProtoMessage() {}

func (x *ProjectConfigDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_adminRpc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectConfigDetailResp.ProtoReflect.Descriptor instead.
func (*ProjectConfigDetailResp) Descriptor() ([]byte, []int) {
	return file_adminRpc_proto_rawDescGZIP(), []int{8}
}

func (x *ProjectConfigDetailResp) GetProjectConfigInfo() *ProjectConfigInfo {
	if x != nil {
		return x.ProjectConfigInfo
	}
	return nil
}

type GiftInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GiftName  string `protobuf:"bytes,2,opt,name=giftName,proto3" json:"giftName,omitempty"`
	ImgUrl    string `protobuf:"bytes,3,opt,name=imgUrl,proto3" json:"imgUrl,omitempty"`
	CreatedAt int64  `protobuf:"varint,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Currency  int64  `protobuf:"varint,5,opt,name=currency,proto3" json:"currency,omitempty"`
	ChargeNum int64  `protobuf:"varint,6,opt,name=chargeNum,proto3" json:"chargeNum,omitempty"`
	GiftAttr  string `protobuf:"bytes,7,opt,name=giftAttr,proto3" json:"giftAttr,omitempty"`
}

func (x *GiftInfo) Reset() {
	*x = GiftInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminRpc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiftInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiftInfo) ProtoMessage() {}

func (x *GiftInfo) ProtoReflect() protoreflect.Message {
	mi := &file_adminRpc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiftInfo.ProtoReflect.Descriptor instead.
func (*GiftInfo) Descriptor() ([]byte, []int) {
	return file_adminRpc_proto_rawDescGZIP(), []int{9}
}

func (x *GiftInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GiftInfo) GetGiftName() string {
	if x != nil {
		return x.GiftName
	}
	return ""
}

func (x *GiftInfo) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

func (x *GiftInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GiftInfo) GetCurrency() int64 {
	if x != nil {
		return x.Currency
	}
	return 0
}

func (x *GiftInfo) GetChargeNum() int64 {
	if x != nil {
		return x.ChargeNum
	}
	return 0
}

func (x *GiftInfo) GetGiftAttr() string {
	if x != nil {
		return x.GiftAttr
	}
	return ""
}

type GiftListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastId   int64 `protobuf:"varint,1,opt,name=lastId,proto3" json:"lastId,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *GiftListReq) Reset() {
	*x = GiftListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminRpc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiftListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiftListReq) ProtoMessage() {}

func (x *GiftListReq) ProtoReflect() protoreflect.Message {
	mi := &file_adminRpc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiftListReq.ProtoReflect.Descriptor instead.
func (*GiftListReq) Descriptor() ([]byte, []int) {
	return file_adminRpc_proto_rawDescGZIP(), []int{10}
}

func (x *GiftListReq) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *GiftListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GiftListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Iret  int64       `protobuf:"varint,1,opt,name=iret,proto3" json:"iret,omitempty"`
	Smsg  string      `protobuf:"bytes,2,opt,name=smsg,proto3" json:"smsg,omitempty"`
	Total int64       `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	List  []*GiftInfo `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GiftListResp) Reset() {
	*x = GiftListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminRpc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiftListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiftListResp) ProtoMessage() {}

func (x *GiftListResp) ProtoReflect() protoreflect.Message {
	mi := &file_adminRpc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiftListResp.ProtoReflect.Descriptor instead.
func (*GiftListResp) Descriptor() ([]byte, []int) {
	return file_adminRpc_proto_rawDescGZIP(), []int{11}
}

func (x *GiftListResp) GetIret() int64 {
	if x != nil {
		return x.Iret
	}
	return 0
}

func (x *GiftListResp) GetSmsg() string {
	if x != nil {
		return x.Smsg
	}
	return ""
}

func (x *GiftListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GiftListResp) GetList() []*GiftInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type GiftItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GiftId int64 `protobuf:"varint,1,opt,name=GiftId,proto3" json:"GiftId,omitempty"`
}

func (x *GiftItemReq) Reset() {
	*x = GiftItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminRpc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiftItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiftItemReq) ProtoMessage() {}

func (x *GiftItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_adminRpc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiftItemReq.ProtoReflect.Descriptor instead.
func (*GiftItemReq) Descriptor() ([]byte, []int) {
	return file_adminRpc_proto_rawDescGZIP(), []int{12}
}

func (x *GiftItemReq) GetGiftId() int64 {
	if x != nil {
		return x.GiftId
	}
	return 0
}

type GiftItemResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Iret      int64  `protobuf:"varint,1,opt,name=Iret,proto3" json:"Iret,omitempty"`
	Smsg      string `protobuf:"bytes,2,opt,name=Smsg,proto3" json:"Smsg,omitempty"`
	Id        int64  `protobuf:"varint,3,opt,name=Id,proto3" json:"Id,omitempty"`
	GiftName  string `protobuf:"bytes,4,opt,name=GiftName,proto3" json:"GiftName,omitempty"`
	ImgUrl    string `protobuf:"bytes,5,opt,name=ImgUrl,proto3" json:"ImgUrl,omitempty"`
	CreatedAt int64  `protobuf:"varint,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Currency  int64  `protobuf:"varint,7,opt,name=Currency,proto3" json:"Currency,omitempty"`
	ChargeNum int64  `protobuf:"varint,8,opt,name=ChargeNum,proto3" json:"ChargeNum,omitempty"`
	GiftAttr  string `protobuf:"bytes,9,opt,name=GiftAttr,proto3" json:"GiftAttr,omitempty"`
}

func (x *GiftItemResp) Reset() {
	*x = GiftItemResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminRpc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GiftItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiftItemResp) ProtoMessage() {}

func (x *GiftItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_adminRpc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiftItemResp.ProtoReflect.Descriptor instead.
func (*GiftItemResp) Descriptor() ([]byte, []int) {
	return file_adminRpc_proto_rawDescGZIP(), []int{13}
}

func (x *GiftItemResp) GetIret() int64 {
	if x != nil {
		return x.Iret
	}
	return 0
}

func (x *GiftItemResp) GetSmsg() string {
	if x != nil {
		return x.Smsg
	}
	return ""
}

func (x *GiftItemResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GiftItemResp) GetGiftName() string {
	if x != nil {
		return x.GiftName
	}
	return ""
}

func (x *GiftItemResp) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

func (x *GiftItemResp) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GiftItemResp) GetCurrency() int64 {
	if x != nil {
		return x.Currency
	}
	return 0
}

func (x *GiftItemResp) GetChargeNum() int64 {
	if x != nil {
		return x.ChargeNum
	}
	return 0
}

func (x *GiftItemResp) GetGiftAttr() string {
	if x != nil {
		return x.GiftAttr
	}
	return ""
}

type AreaInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Level     int64  `protobuf:"varint,2,opt,name=Level,proto3" json:"Level,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Shortname string `protobuf:"bytes,4,opt,name=Shortname,proto3" json:"Shortname,omitempty"`
	Pid       int64  `protobuf:"varint,5,opt,name=Pid,proto3" json:"Pid,omitempty"`
	Longitude string `protobuf:"bytes,6,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Latitude  string `protobuf:"bytes,7,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
}

func (x *AreaInfo) Reset() {
	*x = AreaInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminRpc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AreaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaInfo) ProtoMessage() {}

func (x *AreaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_adminRpc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaInfo.ProtoReflect.Descriptor instead.
func (*AreaInfo) Descriptor() ([]byte, []int) {
	return file_adminRpc_proto_rawDescGZIP(), []int{14}
}

func (x *AreaInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AreaInfo) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *AreaInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AreaInfo) GetShortname() string {
	if x != nil {
		return x.Shortname
	}
	return ""
}

func (x *AreaInfo) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *AreaInfo) GetLongitude() string {
	if x != nil {
		return x.Longitude
	}
	return ""
}

func (x *AreaInfo) GetLatitude() string {
	if x != nil {
		return x.Latitude
	}
	return ""
}

type AreaListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastId   int64 `protobuf:"varint,1,opt,name=lastId,proto3" json:"lastId,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Level    int64 `protobuf:"varint,3,opt,name=Level,proto3" json:"Level,omitempty"`
	Pid      int64 `protobuf:"varint,4,opt,name=Pid,proto3" json:"Pid,omitempty"`
}

func (x *AreaListReq) Reset() {
	*x = AreaListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminRpc_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AreaListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaListReq) ProtoMessage() {}

func (x *AreaListReq) ProtoReflect() protoreflect.Message {
	mi := &file_adminRpc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaListReq.ProtoReflect.Descriptor instead.
func (*AreaListReq) Descriptor() ([]byte, []int) {
	return file_adminRpc_proto_rawDescGZIP(), []int{15}
}

func (x *AreaListReq) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *AreaListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *AreaListReq) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *AreaListReq) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type AreaListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int64       `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*AreaInfo `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *AreaListResp) Reset() {
	*x = AreaListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adminRpc_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AreaListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaListResp) ProtoMessage() {}

func (x *AreaListResp) ProtoReflect() protoreflect.Message {
	mi := &file_adminRpc_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaListResp.ProtoReflect.Descriptor instead.
func (*AreaListResp) Descriptor() ([]byte, []int) {
	return file_adminRpc_proto_rawDescGZIP(), []int{16}
}

func (x *AreaListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AreaListResp) GetList() []*AreaInfo {
	if x != nil {
		return x.List
	}
	return nil
}

var File_adminRpc_proto protoreflect.FileDescriptor

var file_adminRpc_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x97, 0x01, 0x0a, 0x0b, 0x42, 0x61, 0x63, 0x6b, 0x49, 0x6d, 0x67,
	0x43, 0x6f, 0x6e, 0x66, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x6d, 0x61, 0x6c, 0x6c, 0x55,
	0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x6d, 0x61, 0x6c, 0x6c, 0x55,
	0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x66,
	0x0a, 0x14, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x72, 0x79, 0x49, 0x64, 0x22, 0x5a, 0x0a, 0x10, 0x42, 0x61, 0x63, 0x6b, 0x67, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61,
	0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6c, 0x61, 0x73, 0x74,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x22, 0x4e, 0x0a, 0x11, 0x42, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x49, 0x6d, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x23, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62,
	0x2e, 0x42, 0x61, 0x63, 0x6b, 0x49, 0x6d, 0x67, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x22, 0x3a, 0x0a, 0x10, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x0e, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x61, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x22, 0x41,
	0x0a, 0x11, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x2c, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72,
	0x79, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x6e, 0x66, 0x52, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x22, 0xa3, 0x01, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x56, 0x0a, 0x16, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4b, 0x65, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4b, 0x65, 0x79, 0x22,
	0x5e, 0x0a, 0x17, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x43, 0x0a, 0x11, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x11, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0xc2, 0x01, 0x0a, 0x08, 0x47, 0x69, 0x66, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x67, 0x69, 0x66, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x67, 0x69, 0x66, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6d, 0x67, 0x55,
	0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x67, 0x55, 0x72, 0x6c,
	0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68,
	0x61, 0x72, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63,
	0x68, 0x61, 0x72, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x69, 0x66, 0x74,
	0x41, 0x74, 0x74, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x69, 0x66, 0x74,
	0x41, 0x74, 0x74, 0x72, 0x22, 0x41, 0x0a, 0x0b, 0x47, 0x69, 0x66, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x6c, 0x61, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x6e, 0x0a, 0x0c, 0x47, 0x69, 0x66, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x72, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x69, 0x72, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6d, 0x73, 0x67, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x20, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x69, 0x66, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x25, 0x0a, 0x0b, 0x47, 0x69, 0x66, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x69, 0x66, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x47, 0x69, 0x66, 0x74, 0x49, 0x64, 0x22, 0xee,
	0x01, 0x0a, 0x0c, 0x47, 0x69, 0x66, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x12, 0x0a, 0x04, 0x49, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x49,
	0x72, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x53, 0x6d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x69, 0x66, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x47, 0x69, 0x66, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x49, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x4e,
	0x75, 0x6d, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65,
	0x4e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x47, 0x69, 0x66, 0x74, 0x41, 0x74, 0x74, 0x72, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x47, 0x69, 0x66, 0x74, 0x41, 0x74, 0x74, 0x72, 0x22,
	0xae, 0x01, 0x0a, 0x08, 0x41, 0x72, 0x65, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x50, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69,
	0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x22, 0x69, 0x0a, 0x0b, 0x41, 0x72, 0x65, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x6c, 0x61, 0x73, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x6c, 0x61, 0x73, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x50, 0x69, 0x64, 0x22, 0x46, 0x0a, 0x0c, 0x41,
	0x72, 0x65, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x20, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x72, 0x65, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x32, 0xea, 0x02, 0x0a, 0x08, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x70, 0x63,
	0x12, 0x42, 0x0a, 0x13, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x61, 0x63,
	0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x6d, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e,
	0x70, 0x62, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x49, 0x6d, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x3d, 0x0a, 0x0e, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x70,
	0x62, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x4e, 0x0a, 0x13, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x2e, 0x70, 0x62, 0x2e,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x08, 0x67, 0x69, 0x66, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x69, 0x66, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x69, 0x66, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x2d, 0x0a, 0x08, 0x67, 0x69, 0x66, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0f,
	0x2e, 0x70, 0x62, 0x2e, 0x47, 0x69, 0x66, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x1a,
	0x10, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x69, 0x66, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x2d, 0x0a, 0x08, 0x61, 0x72, 0x65, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0f, 0x2e,
	0x70, 0x62, 0x2e, 0x41, 0x72, 0x65, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x10,
	0x2e, 0x70, 0x62, 0x2e, 0x41, 0x72, 0x65, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_adminRpc_proto_rawDescOnce sync.Once
	file_adminRpc_proto_rawDescData = file_adminRpc_proto_rawDesc
)

func file_adminRpc_proto_rawDescGZIP() []byte {
	file_adminRpc_proto_rawDescOnce.Do(func() {
		file_adminRpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_adminRpc_proto_rawDescData)
	})
	return file_adminRpc_proto_rawDescData
}

var file_adminRpc_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_adminRpc_proto_goTypes = []interface{}{
	(*BackImgConf)(nil),             // 0: pb.BackImgConf
	(*DictionaryDetailConf)(nil),    // 1: pb.DictionaryDetailConf
	(*BackgroundImgReq)(nil),        // 2: pb.BackgroundImgReq
	(*BackgroundImgResp)(nil),       // 3: pb.BackgroundImgResp
	(*DictionaryGetReq)(nil),        // 4: pb.DictionaryGetReq
	(*DictionaryGetResp)(nil),       // 5: pb.DictionaryGetResp
	(*ProjectConfigInfo)(nil),       // 6: pb.ProjectConfigInfo
	(*ProjectConfigDetailReq)(nil),  // 7: pb.ProjectConfigDetailReq
	(*ProjectConfigDetailResp)(nil), // 8: pb.ProjectConfigDetailResp
	(*GiftInfo)(nil),                // 9: pb.GiftInfo
	(*GiftListReq)(nil),             // 10: pb.GiftListReq
	(*GiftListResp)(nil),            // 11: pb.GiftListResp
	(*GiftItemReq)(nil),             // 12: pb.GiftItemReq
	(*GiftItemResp)(nil),            // 13: pb.GiftItemResp
	(*AreaInfo)(nil),                // 14: pb.AreaInfo
	(*AreaListReq)(nil),             // 15: pb.AreaListReq
	(*AreaListResp)(nil),            // 16: pb.AreaListResp
}
var file_adminRpc_proto_depIdxs = []int32{
	0,  // 0: pb.BackgroundImgResp.list:type_name -> pb.BackImgConf
	1,  // 1: pb.DictionaryGetResp.list:type_name -> pb.DictionaryDetailConf
	6,  // 2: pb.ProjectConfigDetailResp.projectConfigInfo:type_name -> pb.ProjectConfigInfo
	9,  // 3: pb.GiftListResp.list:type_name -> pb.GiftInfo
	14, // 4: pb.AreaListResp.list:type_name -> pb.AreaInfo
	2,  // 5: pb.adminRpc.backgroundImageList:input_type -> pb.BackgroundImgReq
	4,  // 6: pb.adminRpc.dictionaryList:input_type -> pb.DictionaryGetReq
	7,  // 7: pb.adminRpc.projectConfigDetail:input_type -> pb.ProjectConfigDetailReq
	10, // 8: pb.adminRpc.giftList:input_type -> pb.GiftListReq
	12, // 9: pb.adminRpc.giftItem:input_type -> pb.GiftItemReq
	15, // 10: pb.adminRpc.areaList:input_type -> pb.AreaListReq
	3,  // 11: pb.adminRpc.backgroundImageList:output_type -> pb.BackgroundImgResp
	5,  // 12: pb.adminRpc.dictionaryList:output_type -> pb.DictionaryGetResp
	8,  // 13: pb.adminRpc.projectConfigDetail:output_type -> pb.ProjectConfigDetailResp
	11, // 14: pb.adminRpc.giftList:output_type -> pb.GiftListResp
	13, // 15: pb.adminRpc.giftItem:output_type -> pb.GiftItemResp
	16, // 16: pb.adminRpc.areaList:output_type -> pb.AreaListResp
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_adminRpc_proto_init() }
func file_adminRpc_proto_init() {
	if File_adminRpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_adminRpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackImgConf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adminRpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictionaryDetailConf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adminRpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackgroundImgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adminRpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BackgroundImgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adminRpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictionaryGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adminRpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictionaryGetResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adminRpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectConfigInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adminRpc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectConfigDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adminRpc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProjectConfigDetailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adminRpc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GiftInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adminRpc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GiftListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adminRpc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GiftListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adminRpc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GiftItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adminRpc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GiftItemResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adminRpc_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AreaInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adminRpc_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AreaListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adminRpc_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AreaListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_adminRpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adminRpc_proto_goTypes,
		DependencyIndexes: file_adminRpc_proto_depIdxs,
		MessageInfos:      file_adminRpc_proto_msgTypes,
	}.Build()
	File_adminRpc_proto = out.File
	file_adminRpc_proto_rawDesc = nil
	file_adminRpc_proto_goTypes = nil
	file_adminRpc_proto_depIdxs = nil
}
