// Code generated by goctl. DO NOT EDIT.
package types

type GiftInfo struct {
	Id        int64  `json:"id"`
	GiftName  string `json:"name"`
	ImgUrl    string `json:"image_url"`
	CreatedAt int64  `json:"created_at"`
	Currency  int64  `json:"type"`
	ChargeNum int64  `json:"price"`
	GiftAttr  string `json:"gift_attr"`
}

type GiftListReq struct {
	LastId   int64 `json:"last_id" validate:"omitempty,numeric"`
	PageSize int64 `json:"page_size" validate:"required,omitempty,numeric,max=100,min=1"`
}

type GiftListResp struct {
	Iret  int64       `json:"iret"`
	Smsg  string      `json:"smsg"`
	Total int64       `json:"total"`
	List  []*GiftInfo `json:"list"`
}

type GiftSendReq struct {
	SendTo   string `json:"send_to" validate:"required,omitempty"`
	GiftId   int64  `json:"gift_id" validate:"required,numeric"`
	GiftNum  int64  `json:"gift_num" validate:"required,omitempty,numeric"`
	RoomMark string `json:"room_mark" validate:"required,omitempty"`
}

type GiftSendResp struct {
	Iret int64  `json:"iret"`
	Smsg string `json:"smsg"`
}

type GetItemReq struct {
	GiftId int64 `json:"gift_id" validate:"omitempty,numeric"`
}

type GetItemResp struct {
	Iret int64  `json:"iret"`
	Smsg string `json:"smsg"`
	GiftInfo
}
