// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	gift "social-im/app/gift/cmd/api/internal/handler/gift"
	"social-im/app/gift/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/gift/list",
				Handler: gift.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/gift/send",
				Handler: gift.SendHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/gift/getItem",
				Handler: gift.GetItemHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/gift/v1"),
	)
}
