// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"fmt"

	"github.com/SpectatorNan/gorm-zero/gormc"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"gorm.io/gorm"
)

var (
	cacheGvaSysAreaIdPrefix = "cache:gva:sysArea:id:"
)

type (
	sysAreaModel interface {
		Insert(ctx context.Context, tx *gorm.DB, data *SysArea) error

		FindOne(ctx context.Context, id int64) (*SysArea, error)
		Update(ctx context.Context, tx *gorm.DB, data *SysArea) error

		Delete(ctx context.Context, tx *gorm.DB, id int64) error
		Transaction(ctx context.Context, fn func(db *gorm.DB) error) error
	}

	defaultSysAreaModel struct {
		gormc.CachedConn
		table string
	}

	SysArea struct {
		Id        int64  `gorm:"column:id"`
		Pid       int64  `gorm:"column:pid"`       // 父级
		Name      string `gorm:"column:name"`      // 名称
		Shortname string `gorm:"column:shortname"` // 简称
		Longitude string `gorm:"column:longitude"` // 经度
		Latitude  string `gorm:"column:latitude"`  // 纬度
		Level     int64  `gorm:"column:level"`     // 级别
		Sort      int64  `gorm:"column:sort"`      // 排序
		Status    int64  `gorm:"column:status"`    // 状态1有效
	}
)

func (SysArea) TableName() string {
	return "`sys_area`"
}

func newSysAreaModel(conn *gorm.DB, c cache.CacheConf) *defaultSysAreaModel {
	return &defaultSysAreaModel{
		CachedConn: gormc.NewConn(conn, c),
		table:      "`sys_area`",
	}
}

func (m *defaultSysAreaModel) Insert(ctx context.Context, tx *gorm.DB, data *SysArea) error {

	err := m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(&data).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultSysAreaModel) FindOne(ctx context.Context, id int64) (*SysArea, error) {
	gvaSysAreaIdKey := fmt.Sprintf("%s%v", cacheGvaSysAreaIdPrefix, id)
	var resp SysArea
	err := m.QueryCtx(ctx, &resp, gvaSysAreaIdKey, func(conn *gorm.DB, v interface{}) error {
		return conn.Model(&SysArea{}).Where("`id` = ?", id).First(&resp).Error
	})
	switch err {
	case nil:
		return &resp, nil
	case gormc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysAreaModel) Update(ctx context.Context, tx *gorm.DB, data *SysArea) error {
	old, err := m.FindOne(ctx, data.Id)
	if err != nil && err != ErrNotFound {
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Save(data).Error
	}, m.getCacheKeys(old)...)
	return err
}

func (m *defaultSysAreaModel) getCacheKeys(data *SysArea) []string {
	if data == nil {
		return []string{}
	}
	gvaSysAreaIdKey := fmt.Sprintf("%s%v", cacheGvaSysAreaIdPrefix, data.Id)
	cacheKeys := []string{
		gvaSysAreaIdKey,
	}
	cacheKeys = append(cacheKeys, m.customCacheKeys(data)...)
	return cacheKeys
}

func (m *defaultSysAreaModel) Delete(ctx context.Context, tx *gorm.DB, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		if err == ErrNotFound {
			return nil
		}
		return err
	}
	err = m.ExecCtx(ctx, func(conn *gorm.DB) error {
		db := conn
		if tx != nil {
			db = tx
		}
		return db.Delete(&SysArea{}, id).Error
	}, m.getCacheKeys(data)...)
	return err
}

func (m *defaultSysAreaModel) Transaction(ctx context.Context, fn func(db *gorm.DB) error) error {
	return m.TransactCtx(ctx, fn)
}

func (m *defaultSysAreaModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheGvaSysAreaIdPrefix, primary)
}

func (m *defaultSysAreaModel) queryPrimary(conn *gorm.DB, v, primary interface{}) error {
	return conn.Model(&SysArea{}).Where("`id` = ?", primary).Take(v).Error
}

func (m *defaultSysAreaModel) tableName() string {
	return m.table
}
