// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	room "social-im/app/room/cmd/api/internal/handler/room"
	"social-im/app/room/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/party/create",
				Handler: room.CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/roomLimit/get",
				Handler: room.RoomLimitGetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/party/join",
				Handler: room.JoinHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/party/leave",
				Handler: room.LeaveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/party/remove",
				Handler: room.RemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/party/terminate",
				Handler: room.TerminateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/party/list",
				Handler: room.PartyListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/party/userNumReport",
				Handler: room.UserNumReportHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/party/updateName",
				Handler: room.UpdatePartyNameHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/party/updateBackgroundImg",
				Handler: room.UpdatePartyBackgroundImgHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/prohibition/userAdd",
				Handler: room.ProhibitionUserAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/prohibition/userRemove",
				Handler: room.ProhibitionUserRemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/prohibition/list",
				Handler: room.ProhibitionListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/prohibition/userInfo",
				Handler: room.ProhibitionUserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/room/v1"),
	)
}
