// Code generated by goctl. DO NOT EDIT.
package types

type CommonResp struct {
	Iret int64  `json:"iret"`
	Smsg string `json:"smsg"`
}

type TokenResp struct {
	AccessToken string `json:"accessToken"`
	RtcToken    string `json:"rtcToken"`
	RtmToken    string `json:"rtmToken"`
}

type User struct {
	Id       int64  `json:"id"`
	Mobile   string `json:"mobile"`
	NickName string `json:"nickname"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
	Info     string `json:"info"`
}

type RegisterReq struct {
	Mobile     string `json:"mobile"`
	Password   string `json:"password"`
	Verifycode string `json:"verifycode"`
	RegType    int64  `jaon:"regtype"`
}

type RegisterResp struct {
	CommonResp
	TokenResp
	UserInfo User `json:"userInfo"`
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	CommonResp
	TokenResp
	UserInfo User `json:"userInfo"`
}

type UserInfoReq struct {
	Uid int64 `json:"uid"`
}

type UserInfoResp struct {
	CommonResp
	UserInfo User `json:"userInfo"`
}

type IdentityReq struct {
	Identity string `json:"identity"`
	RealName string `json:"real_name"`
	DeviceId string `json:"device_id"`
}

type IdentityResp struct {
	Res string `json:"res"`
}

type CheckUserIdReq struct {
	Mobile string `json:"mobile"`
}

type CheckUserIdResp struct {
	CommonResp
	UserId    int64 `json:"userId"`
	PwdStatus int64 `json:"pwdStatus"`
}

type UpdateInfoReq struct {
	Uid      int64  `json:"uid"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Sex      int64  `json:"sex"`
	Avatar   string `json:"avatar"`
	Birthday int64  `json:"birthday"`
}

type UpdateInfoResp struct {
	CommonResp
	UserInfo User `json:"userInfo"`
}

type UpdatePwdReq struct {
	Mobile string `json:"mobile"`
	Pwd    string `json:"pwd"`
}

type UpdatePwdResp struct {
	CommonResp
}

type GetRtcTokenReq struct {
	Uid         string `json:"uid"`
	ChannelName string `json:"channelName"`
}

type GetRtcTokenResp struct {
	CommonResp
	RtcToken string `json:"rtcToken"`
}

type GetRtmTokenReq struct {
	Uid string `json:"uid"`
}

type GetRtmTokenResp struct {
	CommonResp
	RtmToken string `json:"rtmToken"`
}

type GetAccessTokenReq struct {
	Uid    string `json:"uid"`
	Mobile string `json:"mobile"`
	Plat   string `json:"plat"`
}

type GetAccessTokenResp struct {
	CommonResp
	AccessToken string `json:"accessToken"`
}

type MicStatus struct {
	Code   int    `json:"code"`
	Status string `json:"status"`
}

type ApplyMicReq struct {
	Room int64 `json:"room"`
	User int64 `json:"user"`
}

type ApplyMicResp struct {
	Status MicStatus `json:"status"`
}

type ApproveMicReq struct {
	Room int64 `json:"room"`
	Uid  int64 `json:"uid"`
	User int64 `json:"user"`
}

type ApproveMicResp struct {
	Status MicStatus `json:"status"`
}

type RejectMicReq struct {
	Room int64 `json:"room"`
	Uid  int64 `json:"uid"`
	User int64 `json:"user"`
}

type RejectMicResp struct {
	Status MicStatus `json:"status"`
}

type RemoveMicReq struct {
	Room int64 `json:"room"`
	Uid  int64 `json:"uid"`
	User int64 `json:"user"`
}

type RemoveMicResp struct {
	Status MicStatus `json:"status"`
}

type ApplyingMicListReq struct {
	Room int64 `json:"room"`
}

type ApplyingMicListResp struct {
	Users []int64 `json:"users"`
}

type OnMicListReq struct {
	Room int64 `json:"room"`
}

type OnMicListResp struct {
	Users []int64 `json:"users"`
}

type InviteMicReq struct {
	Room int64 `json:"room"`
	Uid  int64 `json:"uid"`
	User int64 `json:"user"`
}

type InviteMicResp struct {
	Status MicStatus `json:"status"`
}

type AcceptMicReq struct {
	Room int64 `json:"room"`
	User int64 `json:"user"`
}

type AcceptMicResp struct {
	Status MicStatus `json:"status"`
}

type DeclineMicReq struct {
	Room int64 `json:"room"`
	User int64 `json:"user"`
}

type DeclineMicResp struct {
	Status MicStatus `json:"status"`
}

type StopMicReq struct {
	Room int64 `json:"room"`
	Uid  int64 `json:"uid"`
	User int64 `json:"user"`
}

type StopMicResp struct {
	Status MicStatus `json:"status"`
}

type ResumeMicReq struct {
	Room int64 `json:"room"`
	Uid  int64 `json:"uid"`
	User int64 `json:"user"`
}

type ResumeMicResp struct {
	Status MicStatus `json:"status"`
}

type InviteAdminReq struct {
	Room int64 `json:"room"`
	Uid  int64 `json:"uid"`
	User int64 `json:"user"`
}

type InviteAdminResp struct {
	Status CommonResp `json:"status"`
}

type AcceptAdminReq struct {
	Room int64 `json:"room"`
	User int64 `json:"user"`
}

type AcceptAdminResp struct {
	Status CommonResp `json:"status"`
}

type DeclineAdminReq struct {
	Room int64 `json:"room"`
	User int64 `json:"user"`
}

type DeclineAdminResp struct {
	Status CommonResp `json:"status"`
}

type RoomAdminListReq struct {
	Room int64 `json:"room"`
}

type RoomAdminListResp struct {
	Uids []int64 `json:"uids"`
}

type RemoveAdminReq struct {
	Room int64 `json:"room"`
	Uid  int64 `json:"uid"`
	User int64 `json:"user"`
}

type RemoveAdminResp struct {
	Status CommonResp `json:"status"`
}

type UserFollowReq struct {
	Room int64 `json:"room"`
	Uid  int64 `json:"uid"`  //action 发起的一方uid
	User int64 `json:"user"` //action 作用方的uid
}

type UserFollowResp struct {
	CommonResp
}

type UserunFollowReq struct {
	Room int64 `json:"room"`
	Uid  int64 `json:"uid"`  //action 发起的一方uid
	User int64 `json:"user"` //action 作用方的uid
}

type UserunFollowResp struct {
	CommonResp
}

type UserFollowListReq struct {
	Room int64 `json:"room"`
	Uid  int64 `json:"uid"`
}

type UserFollowListResq struct {
	Users []int64 `json:"users"`
}

type SmsReq struct {
	Mobile string `json:"mobile"`
	Type   string `json:"type"`
}

type SmsResp struct {
	CommonResp
	Msg string `json:"msg"`
}

type SmsRegReq struct {
	Mobile string `json:"mobile"`
	Code   string `json:"code"`
}

type SmsRegResp struct {
	CommonResp
	TokenResp
	UserInfo User   `json:"userInfo"`
	Msg      string `json:"msg"`
}

type SmsLoginReq struct {
	Mobile string `json:"mobile"`
	Code   string `json:"code"`
}

type SmsLoginResp struct {
	CommonResp
	TokenResp
	UserInfo User `json:"userInfo"`
}

type AutoRegReq struct {
	Mobile string `json:"mobile"`
}

type AutoRegResp struct {
	CommonResp
	TokenResp
	UserInfo User   `json:"userInfo"`
	Msg      string `json:"msg"`
}

type SmsVerifyReq struct {
	Mobile string `json:"mobile"`
	Code   string `json:"code"`
	Type   string `json:"type"`
}

type SmsVerifyResp struct {
	CommonResp
	Type string `json:"type"`
	Msg  string `json:"msg"`
}

type UserBase struct {
	Id             int64  `json:"id"`
	Uid            int64  `json:"uid"`
	BodyHeight     string `json:"body_height"`
	Constellation  string `json:"constellation"`
	Education      string `json:"education"`
	School         string `json:"school"`
	Career         string `json:"career"`
	Hobby          string `json:"hobby"`
	ProvinceId     int64  `json:"province_id"`
	CityId         int64  `json:"city_id"`
	DistrictId     int64  `json:"district_id"`
	WorkProvinceId int64  `json:"work_province_id"`
	WorkCityId     int64  `json:"work_city_id"`
	WorkDistrictId int64  `json:"work_district_id"`
	Address        string `json:"address"`
	WorkAddress    string `json:"work_address"`
}

type UpdateBaseReq struct {
	Uid            int64  `json:"uid" validate:"required,numeric,min=1"`
	BodyHeight     string `json:"body_height"`
	Constellation  string `json:"constellation"`
	Education      string `json:"education"`
	School         string `json:"school"`
	Career         string `json:"career"`
	Hobby          string `json:"hobby"`
	ProvinceId     int64  `json:"province_id" validate:"omitempty,numeric"`
	CityId         int64  `json:"city_id" validate:"omitempty,numeric"`
	DistrictId     int64  `json:"district_id" validate:"omitempty,numeric"`
	WorkProvinceId int64  `json:"work_province_id" validate:"omitempty,numeric"`
	WorkCityId     int64  `json:"work_city_id" validate:"omitempty,numeric"`
	WorkDistrictId int64  `json:"work_district_id" validate:"omitempty,numeric"`
	Address        string `json:"address"`
	WorkAddress    string `json:"work_address"`
}

type UpdateBaseResp struct {
	Id  int64 `json:"id"`
	Uid int64 `json:"uid"`
}

type UpdateAboutMeReq struct {
	Uid     int64  `json:"uid" validate:"required,numeric,min=1"`
	AboutMe string `json:"about_me" validate:"omitempty,max=300,min=1"`
}

type UpdateAboutMeResp struct {
	Id  int64 `json:"id"`
	Uid int64 `json:"uid"`
}

type UpdateBackgroundImageReq struct {
	Uid                int64  `json:"uid" validate:"required,numeric,min=1"`
	BackgroundUrl      string `json:"background_url" validate:"required,url"`
	BackgroundSmallUrl string `json:"background_small_url" validate:"required,url"`
}

type UpdateBackgroundImageResp struct {
	Id  int64 `json:"id"`
	Uid int64 `json:"uid"`
}

type GetUserBaseReq struct {
	Uid int64 `json:"uid" validate:"required,numeric,min=1"`
}

type GetUserBaseResp struct {
	Id                 int64    `json:"id"`
	Uid                int64    `json:"uid"`
	BodyHeight         string   `json:"body_height"`
	Constellation      string   `json:"constellation"`
	Education          string   `json:"education"`
	School             string   `json:"school"`
	Career             string   `json:"career"`
	Hobby              string   `json:"hobby"`
	ProvinceId         int64    `json:"province_id"`
	CityId             int64    `json:"city_id"`
	DistrictId         int64    `json:"district_id"`
	WorkProvinceId     int64    `json:"work_province_id"`
	WorkCityId         int64    `json:"work_city_id"`
	WorkDistrictId     int64    `json:"work_district_id"`
	Address            string   `json:"address"`
	WorkAddress        string   `json:"work_address"`
	AboutMe            string   `json:"about_me"`
	BackgroundUrl      string   `json:"background_url"`
	BackgroundSmallUrl string   `json:"background_small_url"`
	DisplayBaseFields  []string `json:"display_base_fields"`
	NotEmptyBaseFields []string `json:"not_empty_base_fields"`
}

type SelectTagReq struct {
	Uid           int64  `json:"uid" validate:"required,numeric,min=1"`
	DisplayFields string `json:"display_fields"`
}

type SelectTagResp struct {
	Id  int64 `json:"id"`
	Uid int64 `json:"uid"`
}
