// Code generated by goctl. DO NOT EDIT.
// Source: adminRpc.proto

package adminrpc

import (
	"context"

	"social-im/app/admin/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AreaInfo                = pb.AreaInfo
	AreaListReq             = pb.AreaListReq
	AreaListResp            = pb.AreaListResp
	BackImgConf             = pb.BackImgConf
	BackgroundImgReq        = pb.BackgroundImgReq
	BackgroundImgResp       = pb.BackgroundImgResp
	DictionaryDetailConf    = pb.DictionaryDetailConf
	DictionaryGetReq        = pb.DictionaryGetReq
	DictionaryGetResp       = pb.DictionaryGetResp
	GiftInfo                = pb.GiftInfo
	GiftItemReq             = pb.GiftItemReq
	GiftItemResp            = pb.GiftItemResp
	GiftListReq             = pb.GiftListReq
	GiftListResp            = pb.GiftListResp
	ProjectConfigDetailReq  = pb.ProjectConfigDetailReq
	ProjectConfigDetailResp = pb.ProjectConfigDetailResp
	ProjectConfigInfo       = pb.ProjectConfigInfo

	AdminRpc interface {
		BackgroundImageList(ctx context.Context, in *BackgroundImgReq, opts ...grpc.CallOption) (*BackgroundImgResp, error)
		DictionaryList(ctx context.Context, in *DictionaryGetReq, opts ...grpc.CallOption) (*DictionaryGetResp, error)
		ProjectConfigDetail(ctx context.Context, in *ProjectConfigDetailReq, opts ...grpc.CallOption) (*ProjectConfigDetailResp, error)
		GiftList(ctx context.Context, in *GiftListReq, opts ...grpc.CallOption) (*GiftListResp, error)
		GiftItem(ctx context.Context, in *GiftItemReq, opts ...grpc.CallOption) (*GiftItemResp, error)
		AreaList(ctx context.Context, in *AreaListReq, opts ...grpc.CallOption) (*AreaListResp, error)
	}

	defaultAdminRpc struct {
		cli zrpc.Client
	}
)

func NewAdminRpc(cli zrpc.Client) AdminRpc {
	return &defaultAdminRpc{
		cli: cli,
	}
}

func (m *defaultAdminRpc) BackgroundImageList(ctx context.Context, in *BackgroundImgReq, opts ...grpc.CallOption) (*BackgroundImgResp, error) {
	client := pb.NewAdminRpcClient(m.cli.Conn())
	return client.BackgroundImageList(ctx, in, opts...)
}

func (m *defaultAdminRpc) DictionaryList(ctx context.Context, in *DictionaryGetReq, opts ...grpc.CallOption) (*DictionaryGetResp, error) {
	client := pb.NewAdminRpcClient(m.cli.Conn())
	return client.DictionaryList(ctx, in, opts...)
}

func (m *defaultAdminRpc) ProjectConfigDetail(ctx context.Context, in *ProjectConfigDetailReq, opts ...grpc.CallOption) (*ProjectConfigDetailResp, error) {
	client := pb.NewAdminRpcClient(m.cli.Conn())
	return client.ProjectConfigDetail(ctx, in, opts...)
}

func (m *defaultAdminRpc) GiftList(ctx context.Context, in *GiftListReq, opts ...grpc.CallOption) (*GiftListResp, error) {
	client := pb.NewAdminRpcClient(m.cli.Conn())
	return client.GiftList(ctx, in, opts...)
}

func (m *defaultAdminRpc) GiftItem(ctx context.Context, in *GiftItemReq, opts ...grpc.CallOption) (*GiftItemResp, error) {
	client := pb.NewAdminRpcClient(m.cli.Conn())
	return client.GiftItem(ctx, in, opts...)
}

func (m *defaultAdminRpc) AreaList(ctx context.Context, in *AreaListReq, opts ...grpc.CallOption) (*AreaListResp, error) {
	client := pb.NewAdminRpcClient(m.cli.Conn())
	return client.AreaList(ctx, in, opts...)
}
